## Shell script installer generator
## Wayne Dec 27, 2018
## v0.1.0
#!/bin/sh
full_path=$1
bin=$(basename $full_path)
folder=${full_path%/$bin}
DATE=`date +%Y-%m-%d`

echo "## Generated by shell script installer generator v0.1.0" > $folder/install.sh
echo "## https://github.com/chronicqazxc/installer-generator" >> $folder/install.sh
echo "## Wayne $DATE" >> $folder/install.sh
echo "ln -s \$(pwd)/$bin /usr/local/bin/$bin" >> $folder/install.sh

if [ -f $folder/install.sh ]
then
	echo "*** $folder/install.sh has been generated***"
  cat $folder/install.sh
else
	echo "*** Generate $folder/install.sh failed***"
fi
echo ""

echo "## Generated by shell script installer generator v0.1.0" > $folder/uninstall.sh
echo "## https://github.com/chronicqazxc/installer-generator" >> $folder/uninstall.sh
echo "## Wayne $DATE" >> $folder/uninstall.sh
echo "rm -rf /usr/local/bin/$bin" >> $folder/uninstall.sh

if [ -f $folder/uninstall.sh ]
then
  echo "*** $folder/uninstall.sh has been generated***"
  cat $folder/uninstall.sh
else
	echo "*** Generate $folder/uninstall.sh failed***"
fi
